# Generated by Django 5.1 on 2024-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="employment_duration",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="employment_position",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="extension",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="fax",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="hit_ec_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="id_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="membership_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="office_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="principal_beneficiary_cell",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="principal_beneficiary_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="residential_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=50,
                null=True,
            ),
        ),
    ]
