# Generated by Django 5.1 on 2024-10-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_member_date_of_birth_alter_member_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="principal_beneficiary_cell",
        ),
        migrations.RemoveField(
            model_name="member",
            name="principal_beneficiary_name",
        ),
    ]
