# Generated by Django 5.1 on 2024-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_member_principal_beneficiary_cell_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="membership_date",
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_date",
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
