# Generated by Django 5.1 on 2024-11-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_customuser_options_member_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        max_digits=6,
                        verbose_name="Monthly Contribution(USD)",
                    ),
                ),
                (
                    "grace_period",
                    models.IntegerField(default=3, verbose_name="Grace Period(Months)"),
                ),
                (
                    "nominee_claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=400,
                        max_digits=6,
                        verbose_name="Nominee Claim Amount(USD)",
                    ),
                ),
                (
                    "principal_claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=6,
                        verbose_name="Principal Claim Amount(USD)",
                    ),
                ),
                (
                    "spouse_claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=6,
                        verbose_name="Spouse Claim Amount(USD)",
                    ),
                ),
                (
                    "child_claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=300,
                        max_digits=6,
                        verbose_name="Child Claim Amount(USD)",
                    ),
                ),
                (
                    "parent_claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=400,
                        max_digits=6,
                        verbose_name="Parent Claim Amount(USD)",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.trustee",
            ),
        ),
    ]
